version: '3.1'
services:
  mysql:
    image: mysql
    container_name: mysql
    hostname: mysql
    ports:
      - '3306:3306'
    command:
      - '--disable-ssl'
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_USER: "demo"
      MYSQL_PASSWORD: "demo"
      MYSQL_DATABASE: "classicmodels"
  # mongo:
  #   image: mongo
  #   ports:
  #     - '27017:27017'
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: "root"
  #     MONGO_INITDB_ROOT_PASSWORD: "root"
  # metabase:
  #   image: metabase/metabase
  #   ports:
  #     - "3000:3000"
  # superset:
  #   image: apache/superset
  #   ports:
  #     - "8080:8088"
networks:
  default:
    name: demo-network
