// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.22.2
// source: app_menu_links.proto

package developer_api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	AppMenuLinks_Index_FullMethodName = "/DeveloperApi.AppMenuLinks/Index"
)

// AppMenuLinksClient is the client API for AppMenuLinks service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AppMenuLinksClient interface {
	Index(ctx context.Context, in *AppMenuLinksIndexRequest, opts ...grpc.CallOption) (*AppMenuLinksIndexRepsonse, error)
}

type appMenuLinksClient struct {
	cc grpc.ClientConnInterface
}

func NewAppMenuLinksClient(cc grpc.ClientConnInterface) AppMenuLinksClient {
	return &appMenuLinksClient{cc}
}

func (c *appMenuLinksClient) Index(ctx context.Context, in *AppMenuLinksIndexRequest, opts ...grpc.CallOption) (*AppMenuLinksIndexRepsonse, error) {
	out := new(AppMenuLinksIndexRepsonse)
	err := c.cc.Invoke(ctx, AppMenuLinks_Index_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AppMenuLinksServer is the server API for AppMenuLinks service.
// All implementations must embed UnimplementedAppMenuLinksServer
// for forward compatibility
type AppMenuLinksServer interface {
	Index(context.Context, *AppMenuLinksIndexRequest) (*AppMenuLinksIndexRepsonse, error)
	mustEmbedUnimplementedAppMenuLinksServer()
}

// UnimplementedAppMenuLinksServer must be embedded to have forward compatible implementations.
type UnimplementedAppMenuLinksServer struct {
}

func (UnimplementedAppMenuLinksServer) Index(context.Context, *AppMenuLinksIndexRequest) (*AppMenuLinksIndexRepsonse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Index not implemented")
}
func (UnimplementedAppMenuLinksServer) mustEmbedUnimplementedAppMenuLinksServer() {}

// UnsafeAppMenuLinksServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AppMenuLinksServer will
// result in compilation errors.
type UnsafeAppMenuLinksServer interface {
	mustEmbedUnimplementedAppMenuLinksServer()
}

func RegisterAppMenuLinksServer(s grpc.ServiceRegistrar, srv AppMenuLinksServer) {
	s.RegisterService(&AppMenuLinks_ServiceDesc, srv)
}

func _AppMenuLinks_Index_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppMenuLinksIndexRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppMenuLinksServer).Index(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AppMenuLinks_Index_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppMenuLinksServer).Index(ctx, req.(*AppMenuLinksIndexRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AppMenuLinks_ServiceDesc is the grpc.ServiceDesc for AppMenuLinks service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AppMenuLinks_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "DeveloperApi.AppMenuLinks",
	HandlerType: (*AppMenuLinksServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Index",
			Handler:    _AppMenuLinks_Index_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "app_menu_links.proto",
}
