// rate_limits.proto

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.22.2
// source: rate_limits.proto

package developer_api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	RateLimits_Show_FullMethodName = "/DeveloperApi.RateLimits/Show"
)

// RateLimitsClient is the client API for RateLimits service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RateLimitsClient interface {
	Show(ctx context.Context, in *RateLimitShowRequest, opts ...grpc.CallOption) (*RateLimitShowResponse, error)
}

type rateLimitsClient struct {
	cc grpc.ClientConnInterface
}

func NewRateLimitsClient(cc grpc.ClientConnInterface) RateLimitsClient {
	return &rateLimitsClient{cc}
}

func (c *rateLimitsClient) Show(ctx context.Context, in *RateLimitShowRequest, opts ...grpc.CallOption) (*RateLimitShowResponse, error) {
	out := new(RateLimitShowResponse)
	err := c.cc.Invoke(ctx, RateLimits_Show_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RateLimitsServer is the server API for RateLimits service.
// All implementations must embed UnimplementedRateLimitsServer
// for forward compatibility
type RateLimitsServer interface {
	Show(context.Context, *RateLimitShowRequest) (*RateLimitShowResponse, error)
	mustEmbedUnimplementedRateLimitsServer()
}

// UnimplementedRateLimitsServer must be embedded to have forward compatible implementations.
type UnimplementedRateLimitsServer struct {
}

func (UnimplementedRateLimitsServer) Show(context.Context, *RateLimitShowRequest) (*RateLimitShowResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Show not implemented")
}
func (UnimplementedRateLimitsServer) mustEmbedUnimplementedRateLimitsServer() {}

// UnsafeRateLimitsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RateLimitsServer will
// result in compilation errors.
type UnsafeRateLimitsServer interface {
	mustEmbedUnimplementedRateLimitsServer()
}

func RegisterRateLimitsServer(s grpc.ServiceRegistrar, srv RateLimitsServer) {
	s.RegisterService(&RateLimits_ServiceDesc, srv)
}

func _RateLimits_Show_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RateLimitShowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RateLimitsServer).Show(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RateLimits_Show_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RateLimitsServer).Show(ctx, req.(*RateLimitShowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RateLimits_ServiceDesc is the grpc.ServiceDesc for RateLimits service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RateLimits_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "DeveloperApi.RateLimits",
	HandlerType: (*RateLimitsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Show",
			Handler:    _RateLimits_Show_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rate_limits.proto",
}
