// rate_limits.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v4.22.2
// source: rate_limits.proto

package developer_api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RateLimitShowRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Domain                  string `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	ApplicationId           string `protobuf:"bytes,2,opt,name=application_id,json=applicationId,proto3" json:"application_id,omitempty"`
	DoorkeeperApplicationId string `protobuf:"bytes,3,opt,name=doorkeeper_application_id,json=doorkeeperApplicationId,proto3" json:"doorkeeper_application_id,omitempty"`
	MerchantId              string `protobuf:"bytes,4,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
}

func (x *RateLimitShowRequest) Reset() {
	*x = RateLimitShowRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rate_limits_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RateLimitShowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RateLimitShowRequest) ProtoMessage() {}

func (x *RateLimitShowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rate_limits_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RateLimitShowRequest.ProtoReflect.Descriptor instead.
func (*RateLimitShowRequest) Descriptor() ([]byte, []int) {
	return file_rate_limits_proto_rawDescGZIP(), []int{0}
}

func (x *RateLimitShowRequest) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *RateLimitShowRequest) GetApplicationId() string {
	if x != nil {
		return x.ApplicationId
	}
	return ""
}

func (x *RateLimitShowRequest) GetDoorkeeperApplicationId() string {
	if x != nil {
		return x.DoorkeeperApplicationId
	}
	return ""
}

func (x *RateLimitShowRequest) GetMerchantId() string {
	if x != nil {
		return x.MerchantId
	}
	return ""
}

type RateLimitShowResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BucketSize int32   `protobuf:"varint,1,opt,name=bucket_size,json=bucketSize,proto3" json:"bucket_size,omitempty"`
	FillRate   float32 `protobuf:"fixed32,2,opt,name=fill_rate,json=fillRate,proto3" json:"fill_rate,omitempty"`
}

func (x *RateLimitShowResponse) Reset() {
	*x = RateLimitShowResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rate_limits_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RateLimitShowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RateLimitShowResponse) ProtoMessage() {}

func (x *RateLimitShowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rate_limits_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RateLimitShowResponse.ProtoReflect.Descriptor instead.
func (*RateLimitShowResponse) Descriptor() ([]byte, []int) {
	return file_rate_limits_proto_rawDescGZIP(), []int{1}
}

func (x *RateLimitShowResponse) GetBucketSize() int32 {
	if x != nil {
		return x.BucketSize
	}
	return 0
}

func (x *RateLimitShowResponse) GetFillRate() float32 {
	if x != nil {
		return x.FillRate
	}
	return 0
}

var File_rate_limits_proto protoreflect.FileDescriptor

var file_rate_limits_proto_rawDesc = []byte{
	0x0a, 0x11, 0x72, 0x61, 0x74, 0x65, 0x5f, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x73, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x44, 0x65, 0x76, 0x65, 0x6c, 0x6f, 0x70, 0x65, 0x72, 0x41, 0x70,
	0x69, 0x22, 0xb2, 0x01, 0x0a, 0x14, 0x52, 0x61, 0x74, 0x65, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x53,
	0x68, 0x6f, 0x77, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x64, 0x6f,
	0x6d, 0x61, 0x69, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x64, 0x6f, 0x6d, 0x61,
	0x69, 0x6e, 0x12, 0x25, 0x0a, 0x0e, 0x61, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x61, 0x70, 0x70, 0x6c,
	0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x3a, 0x0a, 0x19, 0x64, 0x6f, 0x6f,
	0x72, 0x6b, 0x65, 0x65, 0x70, 0x65, 0x72, 0x5f, 0x61, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x17, 0x64, 0x6f,
	0x6f, 0x72, 0x6b, 0x65, 0x65, 0x70, 0x65, 0x72, 0x41, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x6d, 0x65, 0x72, 0x63, 0x68, 0x61, 0x6e,
	0x74, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x6d, 0x65, 0x72, 0x63,
	0x68, 0x61, 0x6e, 0x74, 0x49, 0x64, 0x22, 0x55, 0x0a, 0x15, 0x52, 0x61, 0x74, 0x65, 0x4c, 0x69,
	0x6d, 0x69, 0x74, 0x53, 0x68, 0x6f, 0x77, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x1f, 0x0a, 0x0b, 0x62, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x62, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x53, 0x69, 0x7a, 0x65,
	0x12, 0x1b, 0x0a, 0x09, 0x66, 0x69, 0x6c, 0x6c, 0x5f, 0x72, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x02, 0x52, 0x08, 0x66, 0x69, 0x6c, 0x6c, 0x52, 0x61, 0x74, 0x65, 0x32, 0x5f, 0x0a,
	0x0a, 0x52, 0x61, 0x74, 0x65, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x73, 0x12, 0x51, 0x0a, 0x04, 0x53,
	0x68, 0x6f, 0x77, 0x12, 0x22, 0x2e, 0x44, 0x65, 0x76, 0x65, 0x6c, 0x6f, 0x70, 0x65, 0x72, 0x41,
	0x70, 0x69, 0x2e, 0x52, 0x61, 0x74, 0x65, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x53, 0x68, 0x6f, 0x77,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x23, 0x2e, 0x44, 0x65, 0x76, 0x65, 0x6c, 0x6f,
	0x70, 0x65, 0x72, 0x41, 0x70, 0x69, 0x2e, 0x52, 0x61, 0x74, 0x65, 0x4c, 0x69, 0x6d, 0x69, 0x74,
	0x53, 0x68, 0x6f, 0x77, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x23,
	0x5a, 0x21, 0x64, 0x65, 0x76, 0x65, 0x6c, 0x6f, 0x70, 0x65, 0x72, 0x2d, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x73, 0x2f, 0x67, 0x6f, 0x2f, 0x64, 0x65, 0x76, 0x65, 0x6c, 0x6f, 0x70, 0x65, 0x72, 0x5f,
	0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_rate_limits_proto_rawDescOnce sync.Once
	file_rate_limits_proto_rawDescData = file_rate_limits_proto_rawDesc
)

func file_rate_limits_proto_rawDescGZIP() []byte {
	file_rate_limits_proto_rawDescOnce.Do(func() {
		file_rate_limits_proto_rawDescData = protoimpl.X.CompressGZIP(file_rate_limits_proto_rawDescData)
	})
	return file_rate_limits_proto_rawDescData
}

var file_rate_limits_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_rate_limits_proto_goTypes = []interface{}{
	(*RateLimitShowRequest)(nil),  // 0: DeveloperApi.RateLimitShowRequest
	(*RateLimitShowResponse)(nil), // 1: DeveloperApi.RateLimitShowResponse
}
var file_rate_limits_proto_depIdxs = []int32{
	0, // 0: DeveloperApi.RateLimits.Show:input_type -> DeveloperApi.RateLimitShowRequest
	1, // 1: DeveloperApi.RateLimits.Show:output_type -> DeveloperApi.RateLimitShowResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_rate_limits_proto_init() }
func file_rate_limits_proto_init() {
	if File_rate_limits_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_rate_limits_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RateLimitShowRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rate_limits_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RateLimitShowResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rate_limits_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rate_limits_proto_goTypes,
		DependencyIndexes: file_rate_limits_proto_depIdxs,
		MessageInfos:      file_rate_limits_proto_msgTypes,
	}.Build()
	File_rate_limits_proto = out.File
	file_rate_limits_proto_rawDesc = nil
	file_rate_limits_proto_goTypes = nil
	file_rate_limits_proto_depIdxs = nil
}
