// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v4.22.2
// source: sign_token.proto

package developer_api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Create
type SignTokenCreateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Payload  string `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	ExpireIn int32  `protobuf:"varint,2,opt,name=expire_in,json=expireIn,proto3" json:"expire_in,omitempty"`
	ClientId string `protobuf:"bytes,3,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
}

func (x *SignTokenCreateRequest) Reset() {
	*x = SignTokenCreateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sign_token_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SignTokenCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignTokenCreateRequest) ProtoMessage() {}

func (x *SignTokenCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sign_token_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignTokenCreateRequest.ProtoReflect.Descriptor instead.
func (*SignTokenCreateRequest) Descriptor() ([]byte, []int) {
	return file_sign_token_proto_rawDescGZIP(), []int{0}
}

func (x *SignTokenCreateRequest) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

func (x *SignTokenCreateRequest) GetExpireIn() int32 {
	if x != nil {
		return x.ExpireIn
	}
	return 0
}

func (x *SignTokenCreateRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

type SignTokenCreateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *SignTokenCreateResponse) Reset() {
	*x = SignTokenCreateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sign_token_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SignTokenCreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignTokenCreateResponse) ProtoMessage() {}

func (x *SignTokenCreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sign_token_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignTokenCreateResponse.ProtoReflect.Descriptor instead.
func (*SignTokenCreateResponse) Descriptor() ([]byte, []int) {
	return file_sign_token_proto_rawDescGZIP(), []int{1}
}

func (x *SignTokenCreateResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type SignTokenCreateHmacRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Payload       string `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	ApplicationId string `protobuf:"bytes,2,opt,name=application_id,json=applicationId,proto3" json:"application_id,omitempty"`
}

func (x *SignTokenCreateHmacRequest) Reset() {
	*x = SignTokenCreateHmacRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sign_token_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SignTokenCreateHmacRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignTokenCreateHmacRequest) ProtoMessage() {}

func (x *SignTokenCreateHmacRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sign_token_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignTokenCreateHmacRequest.ProtoReflect.Descriptor instead.
func (*SignTokenCreateHmacRequest) Descriptor() ([]byte, []int) {
	return file_sign_token_proto_rawDescGZIP(), []int{2}
}

func (x *SignTokenCreateHmacRequest) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

func (x *SignTokenCreateHmacRequest) GetApplicationId() string {
	if x != nil {
		return x.ApplicationId
	}
	return ""
}

var File_sign_token_proto protoreflect.FileDescriptor

var file_sign_token_proto_rawDesc = []byte{
	0x0a, 0x10, 0x73, 0x69, 0x67, 0x6e, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x0c, 0x44, 0x65, 0x76, 0x65, 0x6c, 0x6f, 0x70, 0x65, 0x72, 0x41, 0x70, 0x69,
	0x22, 0x6c, 0x0a, 0x16, 0x53, 0x69, 0x67, 0x6e, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x61,
	0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x70, 0x61, 0x79,
	0x6c, 0x6f, 0x61, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x65, 0x78, 0x70, 0x69, 0x72, 0x65, 0x5f, 0x69,
	0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x65, 0x78, 0x70, 0x69, 0x72, 0x65, 0x49,
	0x6e, 0x12, 0x1b, 0x0a, 0x09, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x22, 0x2f,
	0x0a, 0x17, 0x53, 0x69, 0x67, 0x6e, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b,
	0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x22,
	0x5d, 0x0a, 0x1a, 0x53, 0x69, 0x67, 0x6e, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x48, 0x6d, 0x61, 0x63, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a,
	0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x25, 0x0a, 0x0e, 0x61, 0x70, 0x70, 0x6c, 0x69,
	0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0d, 0x61, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x32, 0xc5,
	0x01, 0x0a, 0x09, 0x53, 0x69, 0x67, 0x6e, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x57, 0x0a, 0x06,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x12, 0x24, 0x2e, 0x44, 0x65, 0x76, 0x65, 0x6c, 0x6f, 0x70,
	0x65, 0x72, 0x41, 0x70, 0x69, 0x2e, 0x53, 0x69, 0x67, 0x6e, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x25, 0x2e, 0x44,
	0x65, 0x76, 0x65, 0x6c, 0x6f, 0x70, 0x65, 0x72, 0x41, 0x70, 0x69, 0x2e, 0x53, 0x69, 0x67, 0x6e,
	0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x5f, 0x0a, 0x0a, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x48,
	0x6d, 0x61, 0x63, 0x12, 0x28, 0x2e, 0x44, 0x65, 0x76, 0x65, 0x6c, 0x6f, 0x70, 0x65, 0x72, 0x41,
	0x70, 0x69, 0x2e, 0x53, 0x69, 0x67, 0x6e, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x48, 0x6d, 0x61, 0x63, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x25, 0x2e,
	0x44, 0x65, 0x76, 0x65, 0x6c, 0x6f, 0x70, 0x65, 0x72, 0x41, 0x70, 0x69, 0x2e, 0x53, 0x69, 0x67,
	0x6e, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x23, 0x5a, 0x21, 0x64, 0x65, 0x76, 0x65, 0x6c, 0x6f,
	0x70, 0x65, 0x72, 0x2d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x67, 0x6f, 0x2f, 0x64, 0x65,
	0x76, 0x65, 0x6c, 0x6f, 0x70, 0x65, 0x72, 0x5f, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_sign_token_proto_rawDescOnce sync.Once
	file_sign_token_proto_rawDescData = file_sign_token_proto_rawDesc
)

func file_sign_token_proto_rawDescGZIP() []byte {
	file_sign_token_proto_rawDescOnce.Do(func() {
		file_sign_token_proto_rawDescData = protoimpl.X.CompressGZIP(file_sign_token_proto_rawDescData)
	})
	return file_sign_token_proto_rawDescData
}

var file_sign_token_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_sign_token_proto_goTypes = []interface{}{
	(*SignTokenCreateRequest)(nil),     // 0: DeveloperApi.SignTokenCreateRequest
	(*SignTokenCreateResponse)(nil),    // 1: DeveloperApi.SignTokenCreateResponse
	(*SignTokenCreateHmacRequest)(nil), // 2: DeveloperApi.SignTokenCreateHmacRequest
}
var file_sign_token_proto_depIdxs = []int32{
	0, // 0: DeveloperApi.SignToken.Create:input_type -> DeveloperApi.SignTokenCreateRequest
	2, // 1: DeveloperApi.SignToken.CreateHmac:input_type -> DeveloperApi.SignTokenCreateHmacRequest
	1, // 2: DeveloperApi.SignToken.Create:output_type -> DeveloperApi.SignTokenCreateResponse
	1, // 3: DeveloperApi.SignToken.CreateHmac:output_type -> DeveloperApi.SignTokenCreateResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_sign_token_proto_init() }
func file_sign_token_proto_init() {
	if File_sign_token_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_sign_token_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SignTokenCreateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sign_token_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SignTokenCreateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sign_token_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SignTokenCreateHmacRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_sign_token_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sign_token_proto_goTypes,
		DependencyIndexes: file_sign_token_proto_depIdxs,
		MessageInfos:      file_sign_token_proto_msgTypes,
	}.Build()
	File_sign_token_proto = out.File
	file_sign_token_proto_rawDesc = nil
	file_sign_token_proto_goTypes = nil
	file_sign_token_proto_depIdxs = nil
}
