// user_hints.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v4.22.2
// source: user_hints.proto

package developer_api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserHintStatus int32

const (
	UserHintStatus_SHOW    UserHintStatus = 0
	UserHintStatus_NOTSHOW UserHintStatus = 1
)

// Enum value maps for UserHintStatus.
var (
	UserHintStatus_name = map[int32]string{
		0: "SHOW",
		1: "NOTSHOW",
	}
	UserHintStatus_value = map[string]int32{
		"SHOW":    0,
		"NOTSHOW": 1,
	}
)

func (x UserHintStatus) Enum() *UserHintStatus {
	p := new(UserHintStatus)
	*p = x
	return p
}

func (x UserHintStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UserHintStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_user_hints_proto_enumTypes[0].Descriptor()
}

func (UserHintStatus) Type() protoreflect.EnumType {
	return &file_user_hints_proto_enumTypes[0]
}

func (x UserHintStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UserHintStatus.Descriptor instead.
func (UserHintStatus) EnumDescriptor() ([]byte, []int) {
	return file_user_hints_proto_rawDescGZIP(), []int{0}
}

type UserHint struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId    string         `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Namespace string         `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Subject   string         `protobuf:"bytes,3,opt,name=subject,proto3" json:"subject,omitempty"`
	Status    UserHintStatus `protobuf:"varint,4,opt,name=status,proto3,enum=DeveloperApi.UserHintStatus" json:"status,omitempty"`
	Metadata  string         `protobuf:"bytes,5,opt,name=metadata,proto3" json:"metadata,omitempty"`
	UserType  string         `protobuf:"bytes,6,opt,name=user_type,json=userType,proto3" json:"user_type,omitempty"`
}

func (x *UserHint) Reset() {
	*x = UserHint{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_hints_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserHint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserHint) ProtoMessage() {}

func (x *UserHint) ProtoReflect() protoreflect.Message {
	mi := &file_user_hints_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserHint.ProtoReflect.Descriptor instead.
func (*UserHint) Descriptor() ([]byte, []int) {
	return file_user_hints_proto_rawDescGZIP(), []int{0}
}

func (x *UserHint) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserHint) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *UserHint) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *UserHint) GetStatus() UserHintStatus {
	if x != nil {
		return x.Status
	}
	return UserHintStatus_SHOW
}

func (x *UserHint) GetMetadata() string {
	if x != nil {
		return x.Metadata
	}
	return ""
}

func (x *UserHint) GetUserType() string {
	if x != nil {
		return x.UserType
	}
	return ""
}

type UserHintIndexRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId   string `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UserType string `protobuf:"bytes,2,opt,name=user_type,json=userType,proto3" json:"user_type,omitempty"`
	Subject  string `protobuf:"bytes,3,opt,name=subject,proto3" json:"subject,omitempty"`
}

func (x *UserHintIndexRequest) Reset() {
	*x = UserHintIndexRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_hints_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserHintIndexRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserHintIndexRequest) ProtoMessage() {}

func (x *UserHintIndexRequest) ProtoReflect() protoreflect.Message {
	mi := &file_user_hints_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserHintIndexRequest.ProtoReflect.Descriptor instead.
func (*UserHintIndexRequest) Descriptor() ([]byte, []int) {
	return file_user_hints_proto_rawDescGZIP(), []int{1}
}

func (x *UserHintIndexRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserHintIndexRequest) GetUserType() string {
	if x != nil {
		return x.UserType
	}
	return ""
}

func (x *UserHintIndexRequest) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

type UserHintIndexReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Items []*UserHint `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
}

func (x *UserHintIndexReply) Reset() {
	*x = UserHintIndexReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_user_hints_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserHintIndexReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserHintIndexReply) ProtoMessage() {}

func (x *UserHintIndexReply) ProtoReflect() protoreflect.Message {
	mi := &file_user_hints_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserHintIndexReply.ProtoReflect.Descriptor instead.
func (*UserHintIndexReply) Descriptor() ([]byte, []int) {
	return file_user_hints_proto_rawDescGZIP(), []int{2}
}

func (x *UserHintIndexReply) GetItems() []*UserHint {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_user_hints_proto protoreflect.FileDescriptor

var file_user_hints_proto_rawDesc = []byte{
	0x0a, 0x10, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x68, 0x69, 0x6e, 0x74, 0x73, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x0c, 0x44, 0x65, 0x76, 0x65, 0x6c, 0x6f, 0x70, 0x65, 0x72, 0x41, 0x70, 0x69,
	0x22, 0xca, 0x01, 0x0a, 0x08, 0x55, 0x73, 0x65, 0x72, 0x48, 0x69, 0x6e, 0x74, 0x12, 0x17, 0x0a,
	0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70,
	0x61, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6e, 0x61, 0x6d, 0x65, 0x73,
	0x70, 0x61, 0x63, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x75, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x12, 0x34,
	0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1c,
	0x2e, 0x44, 0x65, 0x76, 0x65, 0x6c, 0x6f, 0x70, 0x65, 0x72, 0x41, 0x70, 0x69, 0x2e, 0x55, 0x73,
	0x65, 0x72, 0x48, 0x69, 0x6e, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61,
	0x12, 0x1b, 0x0a, 0x09, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x54, 0x79, 0x70, 0x65, 0x22, 0x66, 0x0a,
	0x14, 0x55, 0x73, 0x65, 0x72, 0x48, 0x69, 0x6e, 0x74, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1b,
	0x0a, 0x09, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x54, 0x79, 0x70, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73,
	0x75, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x75,
	0x62, 0x6a, 0x65, 0x63, 0x74, 0x22, 0x42, 0x0a, 0x12, 0x55, 0x73, 0x65, 0x72, 0x48, 0x69, 0x6e,
	0x74, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x2c, 0x0a, 0x05, 0x69,
	0x74, 0x65, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x44, 0x65, 0x76,
	0x65, 0x6c, 0x6f, 0x70, 0x65, 0x72, 0x41, 0x70, 0x69, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x48, 0x69,
	0x6e, 0x74, 0x52, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x2a, 0x27, 0x0a, 0x0e, 0x55, 0x73, 0x65,
	0x72, 0x48, 0x69, 0x6e, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x08, 0x0a, 0x04, 0x53,
	0x48, 0x4f, 0x57, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x4e, 0x4f, 0x54, 0x53, 0x48, 0x4f, 0x57,
	0x10, 0x01, 0x32, 0xd8, 0x01, 0x0a, 0x09, 0x55, 0x73, 0x65, 0x72, 0x48, 0x69, 0x6e, 0x74, 0x73,
	0x12, 0x4f, 0x0a, 0x05, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x22, 0x2e, 0x44, 0x65, 0x76, 0x65,
	0x6c, 0x6f, 0x70, 0x65, 0x72, 0x41, 0x70, 0x69, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x48, 0x69, 0x6e,
	0x74, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e,
	0x44, 0x65, 0x76, 0x65, 0x6c, 0x6f, 0x70, 0x65, 0x72, 0x41, 0x70, 0x69, 0x2e, 0x55, 0x73, 0x65,
	0x72, 0x48, 0x69, 0x6e, 0x74, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22,
	0x00, 0x12, 0x3a, 0x0a, 0x06, 0x55, 0x70, 0x73, 0x65, 0x72, 0x74, 0x12, 0x16, 0x2e, 0x44, 0x65,
	0x76, 0x65, 0x6c, 0x6f, 0x70, 0x65, 0x72, 0x41, 0x70, 0x69, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x48,
	0x69, 0x6e, 0x74, 0x1a, 0x16, 0x2e, 0x44, 0x65, 0x76, 0x65, 0x6c, 0x6f, 0x70, 0x65, 0x72, 0x41,
	0x70, 0x69, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x48, 0x69, 0x6e, 0x74, 0x22, 0x00, 0x12, 0x3e, 0x0a,
	0x0a, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4d, 0x61, 0x6e, 0x79, 0x12, 0x16, 0x2e, 0x44, 0x65,
	0x76, 0x65, 0x6c, 0x6f, 0x70, 0x65, 0x72, 0x41, 0x70, 0x69, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x48,
	0x69, 0x6e, 0x74, 0x1a, 0x16, 0x2e, 0x44, 0x65, 0x76, 0x65, 0x6c, 0x6f, 0x70, 0x65, 0x72, 0x41,
	0x70, 0x69, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x48, 0x69, 0x6e, 0x74, 0x22, 0x00, 0x42, 0x23, 0x5a,
	0x21, 0x64, 0x65, 0x76, 0x65, 0x6c, 0x6f, 0x70, 0x65, 0x72, 0x2d, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x73, 0x2f, 0x67, 0x6f, 0x2f, 0x64, 0x65, 0x76, 0x65, 0x6c, 0x6f, 0x70, 0x65, 0x72, 0x5f, 0x61,
	0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_user_hints_proto_rawDescOnce sync.Once
	file_user_hints_proto_rawDescData = file_user_hints_proto_rawDesc
)

func file_user_hints_proto_rawDescGZIP() []byte {
	file_user_hints_proto_rawDescOnce.Do(func() {
		file_user_hints_proto_rawDescData = protoimpl.X.CompressGZIP(file_user_hints_proto_rawDescData)
	})
	return file_user_hints_proto_rawDescData
}

var file_user_hints_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_user_hints_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_user_hints_proto_goTypes = []interface{}{
	(UserHintStatus)(0),          // 0: DeveloperApi.UserHintStatus
	(*UserHint)(nil),             // 1: DeveloperApi.UserHint
	(*UserHintIndexRequest)(nil), // 2: DeveloperApi.UserHintIndexRequest
	(*UserHintIndexReply)(nil),   // 3: DeveloperApi.UserHintIndexReply
}
var file_user_hints_proto_depIdxs = []int32{
	0, // 0: DeveloperApi.UserHint.status:type_name -> DeveloperApi.UserHintStatus
	1, // 1: DeveloperApi.UserHintIndexReply.items:type_name -> DeveloperApi.UserHint
	2, // 2: DeveloperApi.UserHints.Index:input_type -> DeveloperApi.UserHintIndexRequest
	1, // 3: DeveloperApi.UserHints.Upsert:input_type -> DeveloperApi.UserHint
	1, // 4: DeveloperApi.UserHints.UpdateMany:input_type -> DeveloperApi.UserHint
	3, // 5: DeveloperApi.UserHints.Index:output_type -> DeveloperApi.UserHintIndexReply
	1, // 6: DeveloperApi.UserHints.Upsert:output_type -> DeveloperApi.UserHint
	1, // 7: DeveloperApi.UserHints.UpdateMany:output_type -> DeveloperApi.UserHint
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_user_hints_proto_init() }
func file_user_hints_proto_init() {
	if File_user_hints_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_user_hints_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserHint); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_user_hints_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserHintIndexRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_user_hints_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserHintIndexReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_user_hints_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_user_hints_proto_goTypes,
		DependencyIndexes: file_user_hints_proto_depIdxs,
		EnumInfos:         file_user_hints_proto_enumTypes,
		MessageInfos:      file_user_hints_proto_msgTypes,
	}.Build()
	File_user_hints_proto = out.File
	file_user_hints_proto_rawDesc = nil
	file_user_hints_proto_goTypes = nil
	file_user_hints_proto_depIdxs = nil
}
